name: Deploy to production
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repository
        uses: actions/checkout@v3
      - name: Create .env
        run: |
          cp .env.example .env
          sed -i -- "s|%WWWUSER%|$UID|g" .env
          sed -i -- "s|%WWWGROUP%|$UID|g" .env
      - name: Start docker-compose
        run: docker-compose up -d --build
      - name: Install composer
        run: docker exec hospital_web composer install --ignore-platform-reqs
      - name: Install migrate
        run: docker exec hospital_web php artisan migrate
      - name: Test application
        run: docker exec hospital_web composer run tests
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.SSH_HOST }}
      - name: Connect to server
        run: ssh ${{ secrets.SSH_USER }}:${{ secrets.SSH_HOST }}
