name: Deploy to production
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.SSH_HOST }}
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "rm -rf ${{ secrets.DIR }} &&
          git clone git@github.com:develop-dmitry/hospital.git ${{ secrets.DIR }} &&
          cd ${{ secrets.DIR }} &&
          cp .env.example .env &&
          sed -i -- 's|%WWWUSER%|$UID|g' .env &&
          sed -i -- 's|%WWWGROUP%|$UID|g' .env &&
          sed -i -- 's|%APP_NAME%|${{ secrets.APP_NAME }}|g' .env &&
          sed -i -- 's|%APP_DEBUG%|${{ secrets.APP_DEBUG }}|g' .env &&
          sed -i -- 's|%APP_URL%|${{ secrets.APP_URL }}|g' .env &&
          sed -i -- 's|%DB_NAME%|${{ secrets.DB_NAME }}|g' .env &&
          sed -i -- 's|%DB_USERNAME%|${{ secrets.DB_USERNAME }}|g' .env &&
          sed -i -- 's|%DB_PASSWORD%|${{ secrets.DB_PASSWORD }}|g' .env &&
          sed -i -- 's|%REDIS_HOST%|${{ secrets.REDIS_HOST }}|g' .env
          "
