name: PHP Unit Tests
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: develop-dmitry/hospital/.github/workflows/build.yml@main
      - name: Test application
        run: docker exec hospital_web composer run tests
